### ISSUE TITLE
Can't install dependencies for demo

### ISSUE THREAD

**Issue by stolmen** [turn-based/boardgame.io-angular#2]
```
Edwards-MacBook-Pro:boardgame.io-angular edward$ npm i --verbose
npm info it worked if it ends with ok
npm verb cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'i', '--verbose' ]
npm info using npm@6.13.4
npm info using node@v10.16.3
npm verb npm-session c50ae775510ca0a1
npm info lifecycle @~preinstall: @
npm timing stage:loadCurrentTree Completed in 12ms
npm timing stage:loadIdealTree:cloneCurrentTree Completed in 0ms
npm timing stage:loadIdealTree:loadShrinkwrap Completed in 287ms
npm timing stage:loadIdealTree:loadAllDepsIntoIdealTree Completed in 157ms
npm timing stage:loadIdealTree Completed in 465ms
npm timing stage:generateActionsToTake Completed in 483ms
npm verb correctMkdir /Users/edward/.npm/_locks correctMkdir not in flight; initializing
npm verb lock using /Users/edward/.npm/_locks/staging-acd918ac543db2b2.lock for /Users/edward/boardgame.io-angular/node_modules/.staging
npm timing audit submit Completed in 1673ms
npm http fetch POST 200 https://registry.npmjs.org/-/npm/v1/security/audits/quick 1674ms
npm timing audit body Completed in 11ms
npm timing action:extract Completed in 14700ms
npm verb unlock done using /Users/edward/.npm/_locks/staging-acd918ac543db2b2.lock for /Users/edward/boardgame.io-angular/node_modules/.staging
npm timing stage:rollbackFailedOptional Completed in 1ms
npm timing stage:runTopLevelLifecycles Completed in 19227ms
npm verb stack Error: Command failed: git checkout a98b46d0c5fc434d37600f53f9eaaaaef4b2b490
npm verb stack fatal: reference is not a tree: a98b46d0c5fc434d37600f53f9eaaaaef4b2b490
npm verb stack 
npm verb stack     at ChildProcess.exithandler (child_process.js:294:12)
npm verb stack     at ChildProcess.emit (events.js:198:13)
npm verb stack     at maybeClose (internal/child_process.js:982:16)
npm verb stack     at Socket.stream.socket.on (internal/child_process.js:389:11)
npm verb stack     at Socket.emit (events.js:198:13)
npm verb stack     at Pipe._handle.close (net.js:606:12)
npm verb cwd /Users/edward/boardgame.io-angular
npm verb Darwin 19.2.0
npm verb argv "/usr/local/bin/node" "/usr/local/bin/npm" "i" "--verbose"
npm verb node v10.16.3
npm verb npm  v6.13.4
npm ERR! code 128
npm ERR! Command failed: git checkout a98b46d0c5fc434d37600f53f9eaaaaef4b2b490
npm ERR! fatal: reference is not a tree: a98b46d0c5fc434d37600f53f9eaaaaef4b2b490
npm ERR! 
npm verb exit [ 1, true ]
npm timing npm Completed in 19779ms

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/edward/.npm/_logs/2019-12-27T07_04_41_089Z-debug.log
```

**Comment by stolmen** [comment]
```
Edwards-MacBook-Pro:boardgame.io-angular edward$ npm -v
6.13.4
```

**Comment by amitport** [comment]
sorry, I think I missed the notification of this issue. In any case, it should work fine on latest.

**Comment by stolmen** [comment]
thanks :) i'll give it a go when I have a chance.
